package Modelo;
// Generated Feb 4, 2017 9:14:21 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Location generated by hbm2java
 */
public class Location  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String latitude;
     private String longitude;
     private Set meters = new HashSet(0);
     private Set logs = new HashSet(0);

    public Location() {
    }

    public Location(String name, String latitude, String longitude, Set meters, Set logs) {
       this.name = name;
       this.latitude = latitude;
       this.longitude = longitude;
       this.meters = meters;
       this.logs = logs;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }
    public String getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }
    public Set getMeters() {
        return this.meters;
    }
    
    public void setMeters(Set meters) {
        this.meters = meters;
    }
    public Set getLogs() {
        return this.logs;
    }
    
    public void setLogs(Set logs) {
        this.logs = logs;
    }




}


