package Modelo;
// Generated Feb 4, 2017 9:14:21 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Log generated by hbm2java
 */
public class Log  implements java.io.Serializable {


     private int id;
     private Location location;
     private Meter meter;
     private Date time;
     private String event;

    public Log() {
    }

	
    public Log(int id) {
        this.id = id;
    }
    public Log(int id, Location location, Meter meter, Date time, String event) {
       this.id = id;
       this.location = location;
       this.meter = meter;
       this.time = time;
       this.event = event;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Location getLocation() {
        return this.location;
    }
    
    public void setLocation(Location location) {
        this.location = location;
    }
    public Meter getMeter() {
        return this.meter;
    }
    
    public void setMeter(Meter meter) {
        this.meter = meter;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }
    public String getEvent() {
        return this.event;
    }
    
    public void setEvent(String event) {
        this.event = event;
    }




}


