/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Image;
import javafx.scene.control.ToggleButton;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JList;
import javax.swing.JToggleButton;

/**
 *
 * @author ANDRES ARCINIEGAS
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        customInitComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraLogo = new javax.swing.JLabel();
        panelHome = new javax.swing.JPanel();
        medidas3 = new Vista.Medidas();
        panelMedidas1 = new javax.swing.JPanel();
        lbl_hour5 = new javax.swing.JLabel();
        headerSeparato = new javax.swing.JLabel();
        lbl_L1 = new javax.swing.JLabel();
        medida11 = new javax.swing.JLabel();
        unidad11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        medida12 = new javax.swing.JLabel();
        unidad12 = new javax.swing.JLabel();
        medida13 = new javax.swing.JLabel();
        unidad13 = new javax.swing.JLabel();
        title_FP = new javax.swing.JLabel();
        medida14 = new javax.swing.JLabel();
        headerSeparato1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_L2 = new javax.swing.JLabel();
        medida21 = new javax.swing.JLabel();
        unidad21 = new javax.swing.JLabel();
        medida22 = new javax.swing.JLabel();
        unidad22 = new javax.swing.JLabel();
        medida23 = new javax.swing.JLabel();
        unidad23 = new javax.swing.JLabel();
        medida24 = new javax.swing.JLabel();
        headerSeparato2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_L3 = new javax.swing.JLabel();
        medida25 = new javax.swing.JLabel();
        medida26 = new javax.swing.JLabel();
        unidad24 = new javax.swing.JLabel();
        unidad25 = new javax.swing.JLabel();
        medida27 = new javax.swing.JLabel();
        unidad26 = new javax.swing.JLabel();
        medida28 = new javax.swing.JLabel();
        panelDate = new javax.swing.JPanel();
        lbl_hour = new javax.swing.JLabel();
        lbl_hour1 = new javax.swing.JLabel();
        lbl_hour2 = new javax.swing.JLabel();
        btn_close = new javax.swing.JButton();
        panelBtns = new javax.swing.JPanel();
        tog_medidas = new javax.swing.JToggleButton();
        tog_registros = new javax.swing.JToggleButton();
        tog_control = new javax.swing.JToggleButton();
        tog_estimadores = new javax.swing.JToggleButton();
        tog_config = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(800, 480));
        setMinimumSize(new java.awt.Dimension(800, 480));
        setPreferredSize(new java.awt.Dimension(800, 480));
        setResizable(false);
        setSize(800,480);

        barraLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/Header.png"))); // NOI18N

        panelHome.setBackground(new java.awt.Color(255, 255, 255));
        panelHome.setLayout(new java.awt.CardLayout());
        panelHome.add(medidas3, "card3");

        panelMedidas1.setBackground(new java.awt.Color(255, 255, 255));

        lbl_hour5.setFont(new java.awt.Font("Segoe UI Semilight", 0, 36)); // NOI18N
        lbl_hour5.setForeground(new java.awt.Color(51, 51, 51));
        lbl_hour5.setText("Medidas");

        headerSeparato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/lineaHeader.png"))); // NOI18N

        lbl_L1.setFont(new java.awt.Font("Segoe UI Light", 1, 48)); // NOI18N
        lbl_L1.setForeground(new java.awt.Color(47, 85, 151));
        lbl_L1.setText("L1");

        medida11.setFont(new java.awt.Font("Segoe UI Semilight", 0, 32)); // NOI18N
        medida11.setForeground(new java.awt.Color(102, 102, 102));
        medida11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        medida11.setText("120,54");

        unidad11.setFont(new java.awt.Font("Segoe UI Semilight", 0, 30)); // NOI18N
        unidad11.setForeground(new java.awt.Color(102, 102, 102));
        unidad11.setText("V");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/light-green.png"))); // NOI18N

        medida12.setFont(new java.awt.Font("Segoe UI Semilight", 0, 32)); // NOI18N
        medida12.setForeground(new java.awt.Color(102, 102, 102));
        medida12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        medida12.setText("29,84");

        unidad12.setFont(new java.awt.Font("Segoe UI Semilight", 0, 30)); // NOI18N
        unidad12.setForeground(new java.awt.Color(102, 102, 102));
        unidad12.setText("A");

        medida13.setFont(new java.awt.Font("Segoe UI Semilight", 0, 32)); // NOI18N
        medida13.setForeground(new java.awt.Color(102, 102, 102));
        medida13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        medida13.setText("3,591");

        unidad13.setFont(new java.awt.Font("Segoe UI Semilight", 0, 30)); // NOI18N
        unidad13.setForeground(new java.awt.Color(102, 102, 102));
        unidad13.setText("kW");

        title_FP.setFont(new java.awt.Font("Segoe UI Semilight", 0, 36)); // NOI18N
        title_FP.setForeground(new java.awt.Color(102, 102, 102));
        title_FP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_FP.setText("FP");

        medida14.setFont(new java.awt.Font("Segoe UI Semilight", 0, 32)); // NOI18N
        medida14.setForeground(new java.awt.Color(102, 102, 102));
        medida14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        medida14.setText("0,94");

        headerSeparato1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/lineaSeparadorHorizontal.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/light-green.png"))); // NOI18N

        lbl_L2.setFont(new java.awt.Font("Segoe UI Light", 1, 48)); // NOI18N
        lbl_L2.setForeground(new java.awt.Color(47, 85, 151));
        lbl_L2.setText("L2");

        medida21.setFont(new java.awt.Font("Segoe UI Semilight", 0, 32)); // NOI18N
        medida21.setForeground(new java.awt.Color(102, 102, 102));
        medida21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        medida21.setText("120,54");

        unidad21.setFont(new java.awt.Font("Segoe UI Semilight", 0, 30)); // NOI18N
        unidad21.setForeground(new java.awt.Color(102, 102, 102));
        unidad21.setText("V");

        medida22.setFont(new java.awt.Font("Segoe UI Semilight", 0, 32)); // NOI18N
        medida22.setForeground(new java.awt.Color(102, 102, 102));
        medida22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        medida22.setText("29,84");

        unidad22.setFont(new java.awt.Font("Segoe UI Semilight", 0, 30)); // NOI18N
        unidad22.setForeground(new java.awt.Color(102, 102, 102));
        unidad22.setText("A");

        medida23.setFont(new java.awt.Font("Segoe UI Semilight", 0, 32)); // NOI18N
        medida23.setForeground(new java.awt.Color(102, 102, 102));
        medida23.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        medida23.setText("3,591");

        unidad23.setFont(new java.awt.Font("Segoe UI Semilight", 0, 30)); // NOI18N
        unidad23.setForeground(new java.awt.Color(102, 102, 102));
        unidad23.setText("kW");

        medida24.setFont(new java.awt.Font("Segoe UI Semilight", 0, 32)); // NOI18N
        medida24.setForeground(new java.awt.Color(102, 102, 102));
        medida24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        medida24.setText("0,94");

        headerSeparato2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/lineaSeparadorHorizontal.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/light-red.png"))); // NOI18N

        lbl_L3.setFont(new java.awt.Font("Segoe UI Light", 1, 48)); // NOI18N
        lbl_L3.setForeground(new java.awt.Color(47, 85, 151));
        lbl_L3.setText("L3");

        medida25.setFont(new java.awt.Font("Segoe UI Semilight", 0, 32)); // NOI18N
        medida25.setForeground(new java.awt.Color(102, 102, 102));
        medida25.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        medida25.setText("120,54");

        medida26.setFont(new java.awt.Font("Segoe UI Semilight", 0, 32)); // NOI18N
        medida26.setForeground(new java.awt.Color(102, 102, 102));
        medida26.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        medida26.setText("29,84");

        unidad24.setFont(new java.awt.Font("Segoe UI Semilight", 0, 30)); // NOI18N
        unidad24.setForeground(new java.awt.Color(102, 102, 102));
        unidad24.setText("V");

        unidad25.setFont(new java.awt.Font("Segoe UI Semilight", 0, 30)); // NOI18N
        unidad25.setForeground(new java.awt.Color(102, 102, 102));
        unidad25.setText("A");

        medida27.setFont(new java.awt.Font("Segoe UI Semilight", 0, 32)); // NOI18N
        medida27.setForeground(new java.awt.Color(102, 102, 102));
        medida27.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        medida27.setText("3,591");

        unidad26.setFont(new java.awt.Font("Segoe UI Semilight", 0, 30)); // NOI18N
        unidad26.setForeground(new java.awt.Color(102, 102, 102));
        unidad26.setText("kW");

        medida28.setFont(new java.awt.Font("Segoe UI Semilight", 0, 32)); // NOI18N
        medida28.setForeground(new java.awt.Color(102, 102, 102));
        medida28.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        medida28.setText("0,94");

        javax.swing.GroupLayout panelMedidas1Layout = new javax.swing.GroupLayout(panelMedidas1);
        panelMedidas1.setLayout(panelMedidas1Layout);
        panelMedidas1Layout.setHorizontalGroup(
            panelMedidas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMedidas1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(panelMedidas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMedidas1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_L3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(medida25, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(unidad24)
                        .addGap(18, 18, 18)
                        .addComponent(medida26, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(unidad25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(medida27, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(unidad26)
                        .addGap(18, 18, 18)
                        .addComponent(medida28, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelMedidas1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(headerSeparato1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(panelMedidas1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(panelMedidas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(headerSeparato2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelMedidas1Layout.createSequentialGroup()
                                .addComponent(lbl_L2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(medida21, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(unidad21)
                                .addGap(18, 18, 18)
                                .addComponent(medida22, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(unidad22)
                                .addGap(10, 10, 10)
                                .addComponent(medida23, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(unidad23)
                                .addGap(18, 18, 18)
                                .addComponent(medida24, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(panelMedidas1Layout.createSequentialGroup()
                        .addGroup(panelMedidas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelMedidas1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_L1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(medida11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(unidad11)
                                .addGap(18, 18, 18)
                                .addComponent(medida12, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(unidad12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(medida13, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(unidad13))
                            .addGroup(panelMedidas1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(panelMedidas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(headerSeparato)
                                    .addComponent(lbl_hour5))))
                        .addGroup(panelMedidas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelMedidas1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(medida14, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 66, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMedidas1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(title_FP, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52))))))
        );
        panelMedidas1Layout.setVerticalGroup(
            panelMedidas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMedidas1Layout.createSequentialGroup()
                .addGroup(panelMedidas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMedidas1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(title_FP, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(panelMedidas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelMedidas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(medida11, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(unidad11)
                                .addComponent(medida12, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(unidad12)
                                .addComponent(medida13, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(unidad13)
                                .addComponent(medida14, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbl_L1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelMedidas1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_hour5)
                        .addGap(0, 0, 0)
                        .addComponent(headerSeparato, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(headerSeparato1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMedidas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMedidas1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2))
                    .addGroup(panelMedidas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(medida21, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(unidad21)
                        .addComponent(medida22, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(unidad22)
                        .addComponent(medida23, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(unidad23)
                        .addComponent(medida24, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_L2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(headerSeparato2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMedidas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMedidas1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel3))
                    .addGroup(panelMedidas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(medida25, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(unidad24)
                        .addComponent(medida26, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(unidad25)
                        .addComponent(medida27, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(unidad26)
                        .addComponent(medida28, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_L3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelHome.add(panelMedidas1, "card2");

        panelDate.setBackground(new java.awt.Color(255, 255, 255));

        lbl_hour.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lbl_hour.setForeground(new java.awt.Color(102, 102, 102));
        lbl_hour.setText("Domingo,");

        lbl_hour1.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        lbl_hour1.setForeground(new java.awt.Color(102, 102, 102));
        lbl_hour1.setText("00:00");

        lbl_hour2.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lbl_hour2.setForeground(new java.awt.Color(102, 102, 102));
        lbl_hour2.setText("30 de Abril de 2017");

        btn_close.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btn_close.setText("x");
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDateLayout = new javax.swing.GroupLayout(panelDate);
        panelDate.setLayout(panelDateLayout);
        panelDateLayout.setHorizontalGroup(
            panelDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_hour1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_hour2)
                    .addGroup(panelDateLayout.createSequentialGroup()
                        .addComponent(lbl_hour)
                        .addGap(18, 18, 18)
                        .addComponent(btn_close)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDateLayout.setVerticalGroup(
            panelDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDateLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(panelDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDateLayout.createSequentialGroup()
                        .addComponent(lbl_hour)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lbl_hour1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelDateLayout.createSequentialGroup()
                        .addComponent(btn_close)
                        .addGap(1, 1, 1)
                        .addComponent(lbl_hour2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        panelBtns.setBackground(new java.awt.Color(255, 255, 255));

        tog_medidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/btn-medidas-off.png"))); // NOI18N
        tog_medidas.setBorderPainted(false);
        tog_medidas.setContentAreaFilled(false);
        tog_medidas.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/btn-medidas-on.png"))); // NOI18N
        tog_medidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tog_medidasActionPerformed(evt);
            }
        });

        tog_registros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/btn-registros-off.png"))); // NOI18N
        tog_registros.setBorderPainted(false);
        tog_registros.setContentAreaFilled(false);
        tog_registros.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/btn-registros-on.png"))); // NOI18N
        tog_registros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tog_registrosActionPerformed(evt);
            }
        });

        tog_control.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/btn-control-off.png"))); // NOI18N
        tog_control.setBorderPainted(false);
        tog_control.setContentAreaFilled(false);
        tog_control.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/btn-control-on.png"))); // NOI18N
        tog_control.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tog_controlActionPerformed(evt);
            }
        });

        tog_estimadores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/btn-estimadores-off.png"))); // NOI18N
        tog_estimadores.setBorderPainted(false);
        tog_estimadores.setContentAreaFilled(false);
        tog_estimadores.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/btn-estimadores-on.png"))); // NOI18N
        tog_estimadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tog_estimadoresActionPerformed(evt);
            }
        });

        tog_config.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/btn-settings.png"))); // NOI18N
        tog_config.setBorderPainted(false);
        tog_config.setContentAreaFilled(false);
        tog_config.setFocusPainted(false);
        tog_config.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/btn-settings-on.png"))); // NOI18N
        tog_config.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tog_configActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBtnsLayout = new javax.swing.GroupLayout(panelBtns);
        panelBtns.setLayout(panelBtnsLayout);
        panelBtnsLayout.setHorizontalGroup(
            panelBtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBtnsLayout.createSequentialGroup()
                .addComponent(tog_medidas, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tog_registros, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tog_control, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tog_estimadores, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tog_config, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        panelBtnsLayout.setVerticalGroup(
            panelBtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBtnsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panelBtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tog_estimadores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tog_control, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tog_registros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tog_medidas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(panelBtnsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tog_config, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelBtns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(panelHome, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(barraLogo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(barraLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelHome, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelBtns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(panelDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_closeActionPerformed

    private void tog_medidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tog_medidasActionPerformed
        setbtns(0);
    }//GEN-LAST:event_tog_medidasActionPerformed

    private void tog_registrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tog_registrosActionPerformed
        setbtns(1);
    }//GEN-LAST:event_tog_registrosActionPerformed

    private void tog_controlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tog_controlActionPerformed
        setbtns(2);
    }//GEN-LAST:event_tog_controlActionPerformed

    private void tog_estimadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tog_estimadoresActionPerformed
        setbtns(3);
    }//GEN-LAST:event_tog_estimadoresActionPerformed

    private void tog_configActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tog_configActionPerformed
        setbtns(4);
    }//GEN-LAST:event_tog_configActionPerformed
    public static int numbtns = 5;
    public JToggleButton[] togset = new JToggleButton[numbtns];

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel barraLogo;
    private javax.swing.JButton btn_close;
    private javax.swing.JLabel headerSeparato;
    private javax.swing.JLabel headerSeparato1;
    private javax.swing.JLabel headerSeparato2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbl_L1;
    private javax.swing.JLabel lbl_L2;
    private javax.swing.JLabel lbl_L3;
    private javax.swing.JLabel lbl_hour;
    private javax.swing.JLabel lbl_hour1;
    private javax.swing.JLabel lbl_hour2;
    private javax.swing.JLabel lbl_hour5;
    private javax.swing.JLabel medida11;
    private javax.swing.JLabel medida12;
    private javax.swing.JLabel medida13;
    private javax.swing.JLabel medida14;
    private javax.swing.JLabel medida21;
    private javax.swing.JLabel medida22;
    private javax.swing.JLabel medida23;
    private javax.swing.JLabel medida24;
    private javax.swing.JLabel medida25;
    private javax.swing.JLabel medida26;
    private javax.swing.JLabel medida27;
    private javax.swing.JLabel medida28;
    private Vista.Medidas medidas3;
    private javax.swing.JPanel panelBtns;
    private javax.swing.JPanel panelDate;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelMedidas1;
    private javax.swing.JLabel title_FP;
    private javax.swing.JToggleButton tog_config;
    private javax.swing.JToggleButton tog_control;
    private javax.swing.JToggleButton tog_estimadores;
    private javax.swing.JToggleButton tog_medidas;
    private javax.swing.JToggleButton tog_registros;
    private javax.swing.JLabel unidad11;
    private javax.swing.JLabel unidad12;
    private javax.swing.JLabel unidad13;
    private javax.swing.JLabel unidad21;
    private javax.swing.JLabel unidad22;
    private javax.swing.JLabel unidad23;
    private javax.swing.JLabel unidad24;
    private javax.swing.JLabel unidad25;
    private javax.swing.JLabel unidad26;
    // End of variables declaration//GEN-END:variables

    private void customInitComponents() {
        togset[0] = tog_medidas;
        togset[1] = tog_registros;
        togset[2] = tog_control;
        togset[3] = tog_estimadores;
        togset[4] = tog_config;

    }

    private void setbtns(int i) {
        for (int j = 0; j < numbtns; j++) {
            if (j != i) 
                togset[j].setSelected(false);
            else
                togset[j].setSelected(true);            
        }
    }
}
