package Modelo;
// Generated Jan 25, 2017 12:10:19 AM by Hibernate Tools 4.3.1



/**
 * Measure generated by hbm2java
 */
public class Measure  implements java.io.Serializable {


     private Integer id;
     private Measurement measurement;
     private Quantity quantity;
     private double value;

    public Measure() {
    }

    public Measure(Measurement measurement, Quantity quantity, double value) {
       this.measurement = measurement;
       this.quantity = quantity;
       this.value = value;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Measurement getMeasurement() {
        return this.measurement;
    }
    
    public void setMeasurement(Measurement measurement) {
        this.measurement = measurement;
    }
    public Quantity getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Quantity quantity) {
        this.quantity = quantity;
    }
    public double getValue() {
        return this.value;
    }
    
    public void setValue(double value) {
        this.value = value;
    }




}


