package Modelo;
// Generated Jan 25, 2017 12:10:19 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Quantity generated by hbm2java
 */
public class Quantity  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String symbol;
     private String unit;
     private String unitSymbol;
     private Set measures = new HashSet(0);

    public Quantity() {
    }

	
    public Quantity(String name) {
        this.name = name;
    }
    public Quantity(String name, String symbol, String unit, String unitSymbol, Set measures) {
       this.name = name;
       this.symbol = symbol;
       this.unit = unit;
       this.unitSymbol = unitSymbol;
       this.measures = measures;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getSymbol() {
        return this.symbol;
    }
    
    public void setSymbol(String symbol) {
        this.symbol = symbol;
    }
    public String getUnit() {
        return this.unit;
    }
    
    public void setUnit(String unit) {
        this.unit = unit;
    }
    public String getUnitSymbol() {
        return this.unitSymbol;
    }
    
    public void setUnitSymbol(String unitSymbol) {
        this.unitSymbol = unitSymbol;
    }
    public Set getMeasures() {
        return this.measures;
    }
    
    public void setMeasures(Set measures) {
        this.measures = measures;
    }




}


