/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author ANDRES ARCINIEGAS
 */
public class Control extends javax.swing.JPanel {

    /**
     * Creates new form Controles
     */
    public Control() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblL1 = new javax.swing.JLabel();
        lblLineaHeader = new javax.swing.JLabel();
        lblHeader = new javax.swing.JLabel();
        lblUnidad11 = new javax.swing.JLabel();
        lblMedida11 = new javax.swing.JLabel();
        lblMedida12 = new javax.swing.JLabel();
        lblUnidad12 = new javax.swing.JLabel();
        lblMedida13 = new javax.swing.JLabel();
        lblUnidad13 = new javax.swing.JLabel();
        lblSubheader = new javax.swing.JLabel();
        lblMedida14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblL2 = new javax.swing.JLabel();
        lblMedida21 = new javax.swing.JLabel();
        lblMedida22 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblMedida23 = new javax.swing.JLabel();
        lblUnidad22 = new javax.swing.JLabel();
        lblUnidad21 = new javax.swing.JLabel();
        lblUnidad23 = new javax.swing.JLabel();
        lblMedida24 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblL3 = new javax.swing.JLabel();
        lblMedida31 = new javax.swing.JLabel();
        lblMedida32 = new javax.swing.JLabel();
        lblMedida33 = new javax.swing.JLabel();
        lblUnidad32 = new javax.swing.JLabel();
        lblUnidad31 = new javax.swing.JLabel();
        lblUnidad33 = new javax.swing.JLabel();
        lblMedida34 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(800, 325));
        setMinimumSize(new java.awt.Dimension(800, 325));
        setPreferredSize(new java.awt.Dimension(800, 325));

        lblL1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblL1.setForeground(new java.awt.Color(47, 85, 151));
        lblL1.setText("L1");

        lblLineaHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/lineaHeader.png"))); // NOI18N

        lblHeader.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        lblHeader.setForeground(new java.awt.Color(102, 102, 102));
        lblHeader.setText("Control");

        lblUnidad11.setFont(new java.awt.Font("Segoe UI Light", 0, 30)); // NOI18N
        lblUnidad11.setForeground(new java.awt.Color(102, 102, 102));
        lblUnidad11.setText("V");

        lblMedida11.setFont(new java.awt.Font("Segoe UI Light", 0, 44)); // NOI18N
        lblMedida11.setForeground(new java.awt.Color(102, 102, 102));
        lblMedida11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMedida11.setText("120,54");
        lblMedida11.setFocusable(false);
        lblMedida11.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblMedida12.setFont(new java.awt.Font("Segoe UI Light", 0, 44)); // NOI18N
        lblMedida12.setForeground(new java.awt.Color(102, 102, 102));
        lblMedida12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMedida12.setText("29,84");
        lblMedida12.setFocusable(false);
        lblMedida12.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblUnidad12.setFont(new java.awt.Font("Segoe UI Light", 0, 30)); // NOI18N
        lblUnidad12.setForeground(new java.awt.Color(102, 102, 102));
        lblUnidad12.setText("A");

        lblMedida13.setFont(new java.awt.Font("Segoe UI Light", 0, 44)); // NOI18N
        lblMedida13.setForeground(new java.awt.Color(102, 102, 102));
        lblMedida13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMedida13.setText("3,591");
        lblMedida13.setFocusable(false);
        lblMedida13.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblUnidad13.setFont(new java.awt.Font("Segoe UI Light", 0, 30)); // NOI18N
        lblUnidad13.setForeground(new java.awt.Color(102, 102, 102));
        lblUnidad13.setText("kW");

        lblSubheader.setFont(new java.awt.Font("Segoe UI Light", 0, 30)); // NOI18N
        lblSubheader.setForeground(new java.awt.Color(102, 102, 102));
        lblSubheader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSubheader.setText("FP");

        lblMedida14.setFont(new java.awt.Font("Segoe UI Light", 0, 44)); // NOI18N
        lblMedida14.setForeground(new java.awt.Color(102, 102, 102));
        lblMedida14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMedida14.setText("0,94");
        lblMedida14.setFocusable(false);
        lblMedida14.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/light-green.png"))); // NOI18N

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/lineaSeparadorHorizontal.png"))); // NOI18N

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/light-green.png"))); // NOI18N

        lblL2.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblL2.setForeground(new java.awt.Color(47, 85, 151));
        lblL2.setText("L2");

        lblMedida21.setFont(new java.awt.Font("Segoe UI Light", 0, 44)); // NOI18N
        lblMedida21.setForeground(new java.awt.Color(102, 102, 102));
        lblMedida21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMedida21.setText("119,22");
        lblMedida21.setFocusable(false);
        lblMedida21.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblMedida22.setFont(new java.awt.Font("Segoe UI Light", 0, 44)); // NOI18N
        lblMedida22.setForeground(new java.awt.Color(102, 102, 102));
        lblMedida22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMedida22.setText("1,21");
        lblMedida22.setFocusable(false);
        lblMedida22.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/lineaSeparadorHorizontal.png"))); // NOI18N

        lblMedida23.setFont(new java.awt.Font("Segoe UI Light", 0, 44)); // NOI18N
        lblMedida23.setForeground(new java.awt.Color(102, 102, 102));
        lblMedida23.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMedida23.setText("0,144");
        lblMedida23.setFocusable(false);
        lblMedida23.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblUnidad22.setFont(new java.awt.Font("Segoe UI Light", 0, 30)); // NOI18N
        lblUnidad22.setForeground(new java.awt.Color(102, 102, 102));
        lblUnidad22.setText("A");

        lblUnidad21.setFont(new java.awt.Font("Segoe UI Light", 0, 30)); // NOI18N
        lblUnidad21.setForeground(new java.awt.Color(102, 102, 102));
        lblUnidad21.setText("V");

        lblUnidad23.setFont(new java.awt.Font("Segoe UI Light", 0, 30)); // NOI18N
        lblUnidad23.setForeground(new java.awt.Color(102, 102, 102));
        lblUnidad23.setText("kW");

        lblMedida24.setFont(new java.awt.Font("Segoe UI Light", 0, 44)); // NOI18N
        lblMedida24.setForeground(new java.awt.Color(102, 102, 102));
        lblMedida24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMedida24.setText("0,97");
        lblMedida24.setFocusable(false);
        lblMedida24.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/light-red.png"))); // NOI18N

        lblL3.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblL3.setForeground(new java.awt.Color(47, 85, 151));
        lblL3.setText("L3");

        lblMedida31.setFont(new java.awt.Font("Segoe UI Light", 0, 44)); // NOI18N
        lblMedida31.setForeground(new java.awt.Color(102, 102, 102));
        lblMedida31.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMedida31.setText("121,02");
        lblMedida31.setFocusable(false);
        lblMedida31.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblMedida32.setFont(new java.awt.Font("Segoe UI Light", 0, 44)); // NOI18N
        lblMedida32.setForeground(new java.awt.Color(102, 102, 102));
        lblMedida32.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMedida32.setText("0,00");
        lblMedida32.setFocusable(false);
        lblMedida32.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblMedida33.setFont(new java.awt.Font("Segoe UI Light", 0, 44)); // NOI18N
        lblMedida33.setForeground(new java.awt.Color(102, 102, 102));
        lblMedida33.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMedida33.setText("0,00");
        lblMedida33.setFocusable(false);
        lblMedida33.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblUnidad32.setFont(new java.awt.Font("Segoe UI Light", 0, 30)); // NOI18N
        lblUnidad32.setForeground(new java.awt.Color(102, 102, 102));
        lblUnidad32.setText("A");

        lblUnidad31.setFont(new java.awt.Font("Segoe UI Light", 0, 30)); // NOI18N
        lblUnidad31.setForeground(new java.awt.Color(102, 102, 102));
        lblUnidad31.setText("V");

        lblUnidad33.setFont(new java.awt.Font("Segoe UI Light", 0, 30)); // NOI18N
        lblUnidad33.setForeground(new java.awt.Color(102, 102, 102));
        lblUnidad33.setText("kW");

        lblMedida34.setFont(new java.awt.Font("Segoe UI Light", 0, 44)); // NOI18N
        lblMedida34.setForeground(new java.awt.Color(102, 102, 102));
        lblMedida34.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMedida34.setText("0");
        lblMedida34.setFocusable(false);
        lblMedida34.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblL2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblMedida21, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblUnidad21)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblMedida22, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblUnidad22)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblMedida23, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblUnidad23)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblMedida24, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblL3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblMedida31, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblUnidad31)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblMedida32, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblUnidad32)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblMedida33, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblUnidad33)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblMedida34, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 24, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(lblL1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblMedida11, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblUnidad11)
                                .addGap(18, 18, 18)
                                .addComponent(lblMedida12, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblUnidad12)
                                .addGap(18, 18, 18)
                                .addComponent(lblMedida13, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblUnidad13))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLineaHeader)
                                    .addComponent(lblHeader))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblMedida14, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSubheader, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(lblSubheader, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMedida11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblUnidad11, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMedida12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblUnidad12, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMedida13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblUnidad13, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMedida14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblHeader)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLineaHeader)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblL1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGap(29, 29, 29))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel12)
                                .addGap(47, 47, 47)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMedida21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblUnidad21, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMedida22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblUnidad22, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMedida23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblUnidad23, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMedida24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblL2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel16)
                        .addContainerGap(41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblMedida31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblUnidad31, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblMedida32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblUnidad32, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblMedida33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblUnidad33, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblMedida34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblL3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(24, 24, 24))))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblL1;
    private javax.swing.JLabel lblL2;
    private javax.swing.JLabel lblL3;
    private javax.swing.JLabel lblLineaHeader;
    private javax.swing.JLabel lblMedida11;
    private javax.swing.JLabel lblMedida12;
    private javax.swing.JLabel lblMedida13;
    private javax.swing.JLabel lblMedida14;
    private javax.swing.JLabel lblMedida21;
    private javax.swing.JLabel lblMedida22;
    private javax.swing.JLabel lblMedida23;
    private javax.swing.JLabel lblMedida24;
    private javax.swing.JLabel lblMedida31;
    private javax.swing.JLabel lblMedida32;
    private javax.swing.JLabel lblMedida33;
    private javax.swing.JLabel lblMedida34;
    private javax.swing.JLabel lblSubheader;
    private javax.swing.JLabel lblUnidad11;
    private javax.swing.JLabel lblUnidad12;
    private javax.swing.JLabel lblUnidad13;
    private javax.swing.JLabel lblUnidad21;
    private javax.swing.JLabel lblUnidad22;
    private javax.swing.JLabel lblUnidad23;
    private javax.swing.JLabel lblUnidad31;
    private javax.swing.JLabel lblUnidad32;
    private javax.swing.JLabel lblUnidad33;
    // End of variables declaration//GEN-END:variables
}
